# Generated by Django 5.0.6 on 2024-07-03 21:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentamotos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
