# Generated by Django 5.0.6 on 2024-07-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentamotos', '0002_alter_alquiler_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
