# Generated by Django 5.0.6 on 2024-07-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentamotos', '0003_alter_alquiler_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='tarifa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
